# Generated by Django 2.0 on 2017-12-15 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid', '0003_auto_20171215_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to=''),
        ),
    ]
