# Generated by Django 2.0 on 2017-12-15 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid', '0004_auto_20171215_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
