# Generated by Django 2.0 on 2017-12-15 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid', '0005_video_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
