# Generated by Django 2.0 on 2017-12-15 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid', '0006_auto_20171215_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
